version: '3.4'

volumes:
  ui-node_modules:
  api:

services:
  gw:
    image: jrgensen/gateway
    platform: linux/x86_64
    environment:
      PROXY_MAPPINGS: >
        mail:8025
        tilmeld:ui
        sql:phpmyadmin
    ports:
    - 80

  ui:
    build:
      context: .
      target: ui-dev
      dockerfile: docker/Dockerfile
    environment:
      DEBUG: "true"
      NODE_ENV: development
      API_BASEURL: http://tilmeld.dev.nathejk.dk
    volumes:
    - ./vue:/app
    - ui-node_modules:/app/node_modules
    depends_on:
    - gw

  api:
    build:
      context: .
      target: base
      dockerfile: docker/Dockerfile
    environment:
      DB_DSN_RW: bruger:kodeord@tcp(db:3306)/tilmelding?parseTime=true
      #MONOLITH_DB_DSN_RW: root:ib@tcp(dev.nathejk.dk:3306)/nathejk2018?parseTime=true
      COUNTDOWN: "2023-05-02 20:23:00"
      #SENIOR_COUNT: 125
      #GO_BUILD_FLAGS: -race
      STAN_DSN: stan://dev.nathejk.dk:4222/nathejk
      CPSMS_API_URL: https://api.cpsms.dk/v2/send
      CPSMS_API_KEY: token
      SMTP_HOST: mail
      SMTP_PORT: 1025
    volumes:
    - ./go:/app
    - api:/go
    depends_on:
    - gw
    - db

  db:
    image: mariadb:10.8
    environment:
      MYSQL_ROOT_PASSWORD: ib
      MYSQL_DATABASE: tilmelding
      MYSQL_USER: bruger
      MYSQL_PASSWORD: kodeord
      TZ: Europe/Copenhagen

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ib
      PMA_USER: bruger
      PMA_PASSWORD: kodeord
    depends_on:
    - gw

  mail:
    image: mailhog/mailhog:v1.0.1
    platform: linux/x86_64
    restart: unless-stopped
