volumes:
  ui-node_modules:
  api:

networks:
  local:
  traefik:
    external: true

services:
  gw:
    image: jrgensen/gateway
    platform: linux/x86_64
    environment:
      PROXY_MAPPINGS: >
        mail:8025
        tilmelding:ui
        sql:phpmyadmin
    networks:
    - local
    - traefik
    labels:
      traefik.enable: true
      traefik.docker.network: traefik
      traefik.http.routers.tilmelding.rule: Host(`tilmelding.local.nathejk.dk`) || HostRegexp(`.+\.tilmelding\.local\.nathejk\.dk`)

  ui:
    build:
      context: .
      target: ui-dev
      dockerfile: docker/Dockerfile
    environment:
      DEBUG: "true"
      NODE_ENV: development
      API_BASEURL: http://api.tilmelding.dev.nathejk.dk
    volumes:
    - ./vue:/app
    - ui-node_modules:/app/node_modules
    depends_on:
    - gw
    networks:
    - local

  api:
    build:
      context: .
      target: base
      dockerfile: docker/Dockerfile
    environment:
      JETSTREAM_DSN: nats://dev.nathejk.dk:4222
      DB_DSN: bruger:kodeord@tcp(db:3306)/tilmelding?parseTime=true
      SMS_DSN: cpsms://TOKEN@api.cpsms.dk
      #MONOLITH_DB_DSN_RW: root:ib@tcp(dev.nathejk.dk:3306)/nathejk2018?parseTime=true
      PAYMENT_DSN: mobilepay://client_id:client_secret@apitest.vipps.no?Ocp-Apim-Subscription-Key#MSN
      BASEURL: http://tilmelding.dev.nathejk.dk
      COUNTDOWN: "2024-05-02T18:24:00Z"
      COUNTDOWN_VIDEOS: |
        https://nathejk-countdown.s3.eu-central-1.amazonaws.com/videos/anne.mov
        https://nathejk-countdown.s3.eu-central-1.amazonaws.com/videos/caroline.mov
        https://nathejk-countdown.s3.eu-central-1.amazonaws.com/videos/jakob.mov
        https://nathejk-countdown.s3.eu-central-1.amazonaws.com/videos/karsten.mov
        https://nathejk-countdown.s3.eu-central-1.amazonaws.com/videos/klaus.mov
        https://nathejk-countdown.s3.eu-central-1.amazonaws.com/videos/michael.mov
        https://nathejk-countdown.s3.eu-central-1.amazonaws.com/videos/niels.mov
        https://nathejk-countdown.s3.eu-central-1.amazonaws.com/videos/nj.mov
        https://nathejk-countdown.s3.eu-central-1.amazonaws.com/videos/pia.mov
        https://nathejk-countdown.s3.eu-central-1.amazonaws.com/videos/sabrina.mov
        https://nathejk-countdown.s3.eu-central-1.amazonaws.com/videos/sanne.mov
        https://nathejk-countdown.s3.eu-central-1.amazonaws.com/videos/signe.mov
      #SENIOR_COUNT: 125
      #GO_BUILD_FLAGS: -race
      SMTP_HOST: mail
      SMTP_PORT: 1025
    volumes:
    - ./go:/app
    - api:/go
    depends_on:
    - gw
    - db
    networks:
    - local

  db:
    image: mariadb:10.8
    environment:
      MYSQL_ROOT_PASSWORD: ib
      MYSQL_DATABASE: tilmelding
      MYSQL_USER: bruger
      MYSQL_PASSWORD: kodeord
      TZ: Europe/Copenhagen
    networks:
    - local

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ib
      PMA_USER: bruger
      PMA_PASSWORD: kodeord
    depends_on:
    - gw
    networks:
    - local

  mail:
    image: mailhog/mailhog:v1.0.1
    platform: linux/x86_64
    restart: unless-stopped
    networks:
    - local
