CREATE TABLE IF NOT EXISTS deadletter (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    query TEXT NOT NULL,
    error TEXT NOT NULL,
    resolvedAt TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (id)
);
