CREATE TABLE IF NOT EXISTS klan (
    teamId VARCHAR(99) NOT NULL,
    name VARCHAR(99) NOT NULL DEFAULT "",
    groupName VARCHAR(99) NOT NULL DEFAULT "",
    korps VARCHAR(9) NOT NULL DEFAULT "",
    signupStatus VARCHAR(9) NOT NULL DEFAULT "",
    signedUpAt VARCHAR(99) NOT NULL DEFAULT "",
    statusChangedAt VARCHAR(99) NOT NULL DEFAULT "",
    PRIMARY KEY (teamId)
);
